### ISSUE TITLE
Make `cp. [TEXT]` into a link

### ISSUE THREAD

**Issue by hangler** [plot-and-scatter/dchp3#4]
Stefan reported that the text `Cp. Canada boot` should link to the Canada boot headword.

<img width="1265" alt="image" src="https://github.com/plot-and-scatter/dchp3/assets/3538990/04f6a62f-763b-40b9-9015-d8a2e482e259">

**Comment by Shawk031** [comment]
Hmm this problem seems to also exist on the DCHP2 (See below)
![image](https://github.com/plot-and-scatter/dchp3/assets/62414475/6f5493da-a150-461d-92c1-81e04c0d81d3)

So I'll leave this for now
